project:
  type: website
  output-dir: _site

website:
  title: "Kunlei Lian"
  site-url: https://kunlei.github.io/
  google-analytics: "G-DJ30KLH89M"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Books"
        menu:
          - text: "OR-Tools"
            icon: "book"
            href: "https://kunlei.github.io/python-ortools-notes/"
          - text: "Large-Scale Optimization"
            icon: "book"
            href: "https://kunlei.github.io/large-scale-opt-python/"
          - text: "Approaching VRPs"
            icon: "book"
            href: "https://kunlei.github.io/approaching-vrp-java/"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango



